### PR TITLE
Update phpro/grumphp from 0.11.6 to 0.15.2

### PR DESCRIPTION
**Pull request by truls1502**
Referring to #5 

So it would be great to keep the packages to the latest version.

### CODE REVIEW

**Comment by vijaycs85** [comment]
thanks, need to make sure it doesn't break any in Drupal 8.6.x, 8.7.x.

**Comment by truls1502** [comment]
Sure, I am using Drupal 8.7.5 and it worked well. Please doublecheck, or let others to review the PR. 😊

**Comment by vijaycs85** [comment]
I don't know if it is a good idea to allow any version upgrade.

**Comment by truls1502** [comment]
@vijaycs85 - do you have any reason why you want to stay at 0.11.6 and not update to 0.15.2? 😊

**Comment by q0rban** [comment]
I think what @vijaycs85 is saying is that `*` is too permissive. It would be better to be opinionated about an acceptable stability level to be compatible with. What would you be comfortable with @vijaycs85 ? `^0`? `^0.15`?

**Comment by vijaycs85** [comment]
what @q0rban said. Let's keep it ^0.15 for now.

**Comment by vijaycs85** [comment]
committed at https://github.com/vijaycs85/drupal-quality-checker/commit/1a373382874824745a0e1603bf2ca2f338e28033

**Comment by truls1502** [comment]
I would recommend this one `^0`- in this way it is we can go up like this one
https://jubianchi.github.io/semver-check/#/^0/0.16.2
rather than
https://jubianchi.github.io/semver-check/#/^0.15.2/0.16.2 which is not satisfied 

Otherwise, we need to make new commit everytime grumphp released since it is using version such as `0.` not from `1.0`

**Comment by truls1502** [comment]
If you reopen the current PR, you will see the new changes from `^0.15` to `^0`.

**Pull request closed without merging**
